name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-did-you-do
    attributes:
      label: What did you do?
      description: Tell us, what did you do before the issue appeared?
      placeholder: I selected/clicked/opened...
    validations:
      required: true
  - type: textarea
    id: what-did-you-expect
    attributes:
      label: What did you expect to see?
      description: Also tell us, what did you expect to happen?
      placeholder: I expected that...
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What did you see instead?
      description: Finally tell us, what happened, that you did not expect? Screenshots or video recordings help.
      placeholder: What happened instead was...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: DB4S Version
      description: What version of DB Browser for SQLite are you running?
      options:
        - 3.12.2
        - 3.12.1
        - 3.12.0
        - 3.11.x
        - 3.12.99 (nightly)
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - Other
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS version
      description: "Identify the OS version"
      placeholder: "Windows 10, Ubuntu Linux 20.04..."
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output (console, "SQL Log" pane, etc.). This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Prevention against duplicate issues
      description: By submitting this issue, you confirm that you have searched for similar issues before opening a new one. You could comment or subscribe to the found issue.
      options:
        - label: I have searched for similar issues
          required: true
