          name:                   sqlitebrowser  # the name of the snap
          # version:                3.10.1  # the version of the snap
          version: master
          version-script:  printf "`cat currentrelease | head -n 1 `-` git -C . rev-parse --short HEAD`"

          summary:                DB browser for Sqlite  # 79 char long summary
          description:            GUI editor for SQLite databases  # a longer description for the snap
          confinement:            strict  # use "strict" to enforce system access only via declared interfaces

          grade:                  devel
          icon:                   images/sqlitebrowser.svg
          type:                   app

          apps:
            sqlitebrowser:
              command:            desktop-launch $SNAP/wrappers/sqlitebrowser
              desktop:            share/applications/sqlitebrowser.desktop
              environment:
                TMPDIR:           $XDG_RUNTIME_DIR
              plugs:
                # - browser-support
                - desktop
                # - gsettings
                - home
                # - network
                # - opengl
                - unity7
                # - wayland
                - x11
                - removable-media
                # - ssh-keys

          build-packages:
              - build-essential
              - g++
              - qtbase5-dev
              - qttools5-dev
              - qttools5-dev-tools
              - libsqlite3-dev
              - cmake
              - libantlr-dev
              - libsqlcipher-dev
              - libqcustomplot-dev
              # - libx11-xcb1
              # - libx11-xcb-dev
              # - libxcb-xkb-dev
              - libqt5scintilla2-dev
              - git
          parts:
              wrappers:
                  plugin:         dump
                  source:         snap/
              sqlitebrowser:
                  # source-type:    git
                  plugin:         cmake
                  configflags:    ["-DUSE_QT5=True", "-Dsqlcipher=1", "-Wno-dev"]
                  source:         .
              desktop-qt5:
                build-packages:
                - qtbase5-dev
                - dpkg-dev
                make-parameters:
                - FLAVOR=qt5
                plugin:           make
                source:           https://github.com/ubuntu/snapcraft-desktop-helpers.git
                source-subdir:    qt
                stage-packages:
                - libxkbcommon0
                - ttf-ubuntu-font-family
                - dmz-cursor-theme
                - light-themes
                # - adwaita-icon-theme
                # - gnome-themes-standard
                - shared-mime-info
                - libqt5gui5
                - libgdk-pixbuf2.0-0
                - libqt5svg5
                - try:
                  - appmenu-qt5
                # - locales-all
                # - xdg-user-dirs

              dump:
                  plugin:         dump
                  after:
                  - desktop-qt5
                  - sqlitebrowser
                  stage-packages:
                  # - qtbase5-dev
                  # - libqt5gui5
                  # - libqt4gui4
                  # - libxkbcommon0
                  # - libxkbfile1
                  # - gtk2-engines
                  - libc6
                  # - gtk2-engines-oxygen
                  # - gtk3-engines-breeze
                  - libgcc1
                  # - libqcustomplot1.3
                  # - libqt5network5
                  # - libqt5scintilla2-12v5
                  - libsqlite3-0
                  - libstdc++6
                  - libsqlcipher-dev
                  - libatk-adaptor
                  - libgail-common
                  filesets:
                      wanted:
                      # - etc/*
                      # - lib/*
                      - bin/*
                      #- share/icons/hicolor/256x256/apps/*
                      - share/*
                      # - usr/lib/*-linux-gnu/libsqlcipher.so.0
                      # - usr/lib/*-linux-gnu/libdb*
                      # - usr/lib/*-linux-gnu/libz.so*
                      # - usr/share/*
                      # - usr/share/doc
                      # - usr/share/man
                      # - usr/share/lintian
                      # - usr/bin/sqlitebrowser
                      # - usr/share/applications/sqlitebrowser.desktop
                      # - usr/lib/*
                      # - usr/lib/*-linux-gnu/*
                      # - usr/lib/*
                      # - lib/*-linux-gnu/*
                      # - usr/lib/x86_64-linux-gnu/mesa/*
                      # - usr/lib/*-linux-gnu/qt5/plugins/*
                  prime:
                  - $wanted
