name: Publish to WinGet

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@b7370d4d152efdce803a26cc6ca9eee58cb2ad54 # v2
        with:
          identifier: DBBrowserForSQLite.DBBrowserForSQLite
          installers-regex: '\.msi$'  # Only .msi files
          token: ${{ secrets.WINGET_TOKEN }}
